services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - pbdata:/pb/pb_data

  web:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      POCKETBASE_URL: http://pocketbase:8090
      ORIGIN: http://localhost:3000
    depends_on:
      - pocketbase
    restart: unless-stopped

volumes:
  pbdata:
